services:
  email-newsletter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newsletter
    ports:
      - "5432:5432"
